### ISSUE TITLE
[Feature Request] Add the ability to specify what moons get white rocks, ice caves, and amethyst caves

### ISSUE THREAD

**Issue by Reshirou** [ButteryStancakes/Chameleon#1]
Not sure how feasible it is, but it would be really nice to be able to specify what modded moons do and do not get Amethyst or Ice

**Comment by ButteryStancakes** [comment]
In the future I would like to expand on this so it is more compatible with custom content. For now ice moons should automatically apply to any snowy moon mods (although for right now, the other variants are locked to pre-defined vanilla levels)

**Comment by Reshirou** [comment]
Yeah I noticed modded moons get ice rocks, but it would also be nice to specifically choose for some snow moons to get original rocks if it works thematically for diversity

"Old Dine" comes to mind for a gimmick

**Comment by ButteryStancakes** [comment]
_Probably_ in the v1.2 update I will add the ability to set custom interior weights on a per-moon basis, which should address your use case once it's ready. :)

**Comment by ButteryStancakes** [comment]
This is supported in v1.2. I will close this issue once I release on Thunderstore
