### ISSUE TITLE
[Feedback] merge some features from ur main fixes mod, and add `immersive_visor` if u can

### ISSUE THREAD

**Issue by CoolLKKPS** [ButteryStancakes/Chameleon#4]
1. for [this issue ticket](https://github.com/ButteryStancakes/ButteryFixes/issues/19), this is for [#15](https://github.com/ButteryStancakes/ButteryFixes/issues/15), `spacesunshine` mod also can do some, that issue bc user disabled the `shadow` entirely
2. when user installed `shipwindow` mod, this feature is a bit of a disruption to the immersion, as invisible light sources can create lighting and shadows
bc all those issues, i recommend merge this feature to ur `Chameleon` mod, and i do like to see more immersive things, i really want `immersive_visor` mod features back actually

**Comment by ButteryStancakes** [comment]
I am considering moving some of this stuff to Chameleon, although I should clarify that the reason it's in ButteryFixes currently is because it's restoring a v38 feature that was removed in v40. I will have a look at improving this soon

**Comment by CoolLKKPS** [comment]
after test, no vanilla support, btw, will cause dungeon de-sync

**Comment by ButteryStancakes** [comment]
I have merged the planet sun into this mod and made it a config setting in 1.2.3
